"""Add AppSetting model and collection_method field

Revision ID: 102d8aa73a95
Revises: 859b73104dae
Create Date: 2026-02-06 10:20:27.813391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102d8aa73a95'
down_revision = '859b73104dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_setting')
    # ### end Alembic commands ###
