"""buyer_order_delivery_fee_fields

Revision ID: 1510d2f4b483
Revises: 473f85b36d1a
Create Date: 2026-06-14 21:20:33.623208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1510d2f4b483'
down_revision = '473f85b36d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_zone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('is_flexible_delivery', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('flexible_discount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('sales_tax', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('distance_miles', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('items_subtotal', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('total_paid', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('stripe_checkout_session_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_order', schema=None) as batch_op:
        batch_op.drop_column('stripe_checkout_session_id')
        batch_op.drop_column('total_paid')
        batch_op.drop_column('items_subtotal')
        batch_op.drop_column('distance_miles')
        batch_op.drop_column('sales_tax')
        batch_op.drop_column('flexible_discount')
        batch_op.drop_column('is_flexible_delivery')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_zone')

    # ### end Alembic commands ###
