"""in-person sale: sold_in_person, amount_collected, sold_by

Revision ID: 2f3c72041bc7
Revises: 8f8ee5fbe35d
Create Date: 2026-08-13 18:17:53.468317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3c72041bc7'
down_revision = '8f8ee5fbe35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item',
                  sa.Column('sold_in_person', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('inventory_item',
                  sa.Column('amount_collected', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('inventory_item', sa.Column('sold_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_inventory_item_sold_by_id_user', 'inventory_item', 'user',
                          ['sold_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inventory_item_sold_by_id_user', 'inventory_item', type_='foreignkey')
    op.drop_column('inventory_item', 'sold_by_id')
    op.drop_column('inventory_item', 'amount_collected')
    op.drop_column('inventory_item', 'sold_in_person')

    # ### end Alembic commands ###
