"""delivery stop loaded tracking

Revision ID: 309be0f86e10
Revises: 9fa5a550a9ca
Create Date: 2026-08-19 06:43:54.438093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309be0f86e10'
down_revision = '9fa5a550a9ca'
branch_labels = None
depends_on = None


# Autogenerated as batch_alter_table with an unnamed FK; rewritten as plain ALTERs.
# Both local and production are Postgres — batch mode is SQLite scaffolding, and an
# unnamed constraint leaves downgrade() with nothing to drop.

def upgrade():
    op.add_column('delivery_stop', sa.Column('loaded_at', sa.DateTime(), nullable=True))
    op.add_column('delivery_stop', sa.Column('loaded_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_delivery_stop_loaded_by_id_user', 'delivery_stop', 'user',
        ['loaded_by_id'], ['id'],
    )


def downgrade():
    op.drop_constraint('fk_delivery_stop_loaded_by_id_user', 'delivery_stop',
                       type_='foreignkey')
    op.drop_column('delivery_stop', 'loaded_by_id')
    op.drop_column('delivery_stop', 'loaded_at')
