"""Add payout tracking fields

Revision ID: 35a5d88ba744
Revises: f8bf88f1fb8d
Create Date: 2026-02-06 09:27:17.722037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a5d88ba744'
down_revision = 'f8bf88f1fb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payout_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('payout_sent')
        batch_op.drop_column('sold_at')

    # ### end Alembic commands ###
