"""appsetting_value_text

Revision ID: 473f85b36d1a
Revises: 9001e2c1e90c
Create Date: 2026-06-04 21:33:22.758011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473f85b36d1a'
down_revision = '9001e2c1e90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
