"""delivery stop proof of delivery photo

Revision ID: 543e48c154eb
Revises: e5b417bf82ce
Create Date: 2026-08-19 06:55:20.566919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543e48c154eb'
down_revision = 'e5b417bf82ce'
branch_labels = None
depends_on = None


# Autogenerated as batch_alter_table (SQLite scaffolding); both environments are
# Postgres, so this is a plain ALTER.

def upgrade():
    op.add_column('delivery_stop',
                  sa.Column('pod_photo_url', sa.String(length=300), nullable=True))


def downgrade():
    op.drop_column('delivery_stop', 'pod_photo_url')
