"""add_captured_by_id_to_inventory_item

Revision ID: 576d29191e72
Revises: 62fbbcb3d3ed
Create Date: 2026-05-07 18:27:58.506373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576d29191e72'
down_revision = '62fbbcb3d3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captured_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_item_captured_by_id', 'user', ['captured_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_item_captured_by_id', type_='foreignkey')
        batch_op.drop_column('captured_by_id')

    # ### end Alembic commands ###
