"""shift_assignment_completed_at

Revision ID: 6108e1af17ff
Revises: e75123cd96f0
Create Date: 2026-04-07 23:53:33.794169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6108e1af17ff'
down_revision = 'e75123cd96f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
