"""add_quick_capture_fields

Revision ID: 62fbbcb3d3ed
Revises: 937b2a747a2f
Create Date: 2026-05-07 17:16:45.730367

"""
from alembic import op
import sqlalchemy as sa
import secrets


# revision identifiers, used by Alembic.
revision = '62fbbcb3d3ed'
down_revision = '937b2a747a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quick_capture', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('quick_capture_shift_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inventory_item_quick_capture_shift_id', 'shift', ['quick_capture_shift_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal_account', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Seed the internal "Campus Swap" account if not already present
    conn = op.get_bind()
    existing = conn.execute(
        sa.text('SELECT id FROM "user" WHERE email = \'internal@campusswap.com\'')
    ).fetchone()
    if not existing:
        conn.execute(
            sa.text(
                'INSERT INTO "user" (email, full_name, password_hash, is_seller, is_worker, is_admin, '
                "is_super_admin, is_internal_account, payout_rate, has_paid_boost, sms_opted_out, "
                "referral_source, unsubscribed) "
                "VALUES ('internal@campusswap.com', 'Campus Swap', :pw, TRUE, FALSE, FALSE, FALSE, TRUE, 0, FALSE, FALSE, 'internal', FALSE)"
            ),
            {"pw": secrets.token_hex(30)}
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_internal_account')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_item_quick_capture_shift_id', type_='foreignkey')
        batch_op.drop_column('quick_capture_shift_id')
        batch_op.drop_column('is_quick_capture')

    # ### end Alembic commands ###
