"""worker accounts

Revision ID: 64b6d59bc796
Revises: o3p4q5r6s7t8
Create Date: 2026-04-06 01:48:39.012003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b6d59bc796'
down_revision = 'o3p4q5r6s7t8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unc_year', sa.String(length=20), nullable=True),
    sa.Column('role_pref', sa.String(length=20), nullable=True),
    sa.Column('why_blurb', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('worker_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('mon_am', sa.Boolean(), nullable=True),
    sa.Column('mon_pm', sa.Boolean(), nullable=True),
    sa.Column('tue_am', sa.Boolean(), nullable=True),
    sa.Column('tue_pm', sa.Boolean(), nullable=True),
    sa.Column('wed_am', sa.Boolean(), nullable=True),
    sa.Column('wed_pm', sa.Boolean(), nullable=True),
    sa.Column('thu_am', sa.Boolean(), nullable=True),
    sa.Column('thu_pm', sa.Boolean(), nullable=True),
    sa.Column('fri_am', sa.Boolean(), nullable=True),
    sa.Column('fri_pm', sa.Boolean(), nullable=True),
    sa.Column('sat_am', sa.Boolean(), nullable=True),
    sa.Column('sat_pm', sa.Boolean(), nullable=True),
    sa.Column('sun_am', sa.Boolean(), nullable=True),
    sa.Column('sun_pm', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_worker_avail_user_week')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_worker', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('worker_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('worker_role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('worker_role')
        batch_op.drop_column('worker_status')
        batch_op.drop_column('is_worker')

    op.drop_table('worker_availability')
    op.drop_table('worker_application')
    # ### end Alembic commands ###
