"""shift_assignment_truck_number

Revision ID: 69ddb3d57f86
Revises: e11efc9583e7
Create Date: 2026-04-07 11:14:09.673084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ddb3d57f86'
down_revision = 'e11efc9583e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignment', schema=None) as batch_op:
        batch_op.drop_column('truck_number')

    # ### end Alembic commands ###
