"""Add stripe fields, payment_declined, is_large

Revision ID: 6ac62424b704
Revises: suggested_price
Create Date: 2026-02-10 14:38:28.479220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac62424b704'
down_revision = 'suggested_price'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_large', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_declined', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_method_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stripe_payment_method_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('payment_declined')

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('is_large')

    # ### end Alembic commands ###
