"""add_placement_status_to_inventory_item

Revision ID: 75591ac8d320
Revises: 1177e795033f
Create Date: 2026-05-27 16:06:17.278733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75591ac8d320'
down_revision = '1177e795033f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('needs_photo_refresh', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('needs_photo_refresh')
        batch_op.drop_column('placement_status')

    # ### end Alembic commands ###
