"""add_delivery_models

Revision ID: 765e62e00dca
Revises: fced86d80945
Create Date: 2026-05-29 16:07:17.480399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765e62e00dca'
down_revision = 'fced86d80945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('started_by_id', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['started_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id')
    )
    op.create_table('delivery_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('buyer_order_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('capacity_warning', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_order_id'], ['buyer_order.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'buyer_order_id', name='uq_delivery_stop_shift_order')
    )
    op.add_column('buyer_order', sa.Column('delivered_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buyer_order', 'delivered_at')

    op.drop_table('delivery_stop')
    op.drop_table('delivery_run')
    # ### end Alembic commands ###
