"""pickup_access_type_floor_off_campus_complex

Revision ID: 773c1d40cca8
Revises: cc26a70ffae9
Create Date: 2026-04-13 23:23:39.532319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773c1d40cca8'
down_revision = 'cc26a70ffae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_access_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pickup_floor', sa.Integer(), nullable=True))
        batch_op.alter_column('pickup_note',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    # Data migration: rename legacy 'off_campus' → 'off_campus_other'
    op.execute("UPDATE \"user\" SET pickup_location_type = 'off_campus_other' WHERE pickup_location_type = 'off_campus'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pickup_note',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('pickup_floor')
        batch_op.drop_column('pickup_access_type')

    # ### end Alembic commands ###
