"""add_needs_new_photo_flag

Revision ID: 7978e1bce77b
Revises: 691e3287c51c
Create Date: 2026-05-28 19:35:39.661109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7978e1bce77b'
down_revision = '691e3287c51c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_new_photo', sa.Boolean(), server_default='0', nullable=False))


def downgrade_unused():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('digest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('count_in_stock', sa.Integer(), nullable=True),
    sa.Column('default_unit_size', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_notify_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temp_upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_upload_session_token'), ['session_token'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_campus_director', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('campus_director_school', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pickup_address', sa.String(length=200), nullable=True),
    sa.Column('pickup_location_type', sa.String(length=20), nullable=True),
    sa.Column('pickup_dorm', sa.String(length=80), nullable=True),
    sa.Column('pickup_room', sa.String(length=20), nullable=True),
    sa.Column('pickup_note', sa.String(length=500), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('pickup_access_type', sa.String(length=20), nullable=True),
    sa.Column('pickup_floor', sa.Integer(), nullable=True),
    sa.Column('pickup_partner_building', sa.String(length=100), nullable=True),
    sa.Column('payout_method', sa.String(length=20), nullable=True),
    sa.Column('payout_handle', sa.String(length=100), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_declined', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=120), nullable=True),
    sa.Column('referral_source', sa.String(length=50), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=120), nullable=True),
    sa.Column('pickup_week', sa.String(length=10), nullable=True),
    sa.Column('pickup_time_preference', sa.String(length=20), nullable=True),
    sa.Column('moveout_date', sa.Date(), nullable=True),
    sa.Column('is_worker', sa.Boolean(), nullable=True),
    sa.Column('worker_status', sa.String(length=20), nullable=True),
    sa.Column('worker_role', sa.String(length=20), nullable=True),
    sa.Column('referral_code', sa.String(length=8), nullable=True),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('payout_rate', sa.Integer(), nullable=False),
    sa.Column('has_paid_boost', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sms_opted_out', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_internal_account', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_tutorial_user', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('class_year', sa.String(length=20), nullable=True),
    sa.Column('is_proxy_account', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('proxy_temp_password', sa.String(length=20), nullable=True),
    sa.Column('proxy_claim_token', sa.String(length=64), nullable=True),
    sa.Column('proxy_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('proxy_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('proxy_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('proxy_note', sa.String(length=500), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('proxy_claim_token'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    op.create_table('shift_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_tutorial', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start', 'is_tutorial', name='uq_shift_week_week_start_is_tutorial')
    )
    op.create_table('storage_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('location_note', sa.Text(), nullable=True),
    sa.Column('capacity_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_full', sa.Boolean(), nullable=True),
    sa.Column('snapshot_capacity', sa.Float(), nullable=True),
    sa.Column('size_sqft', sa.Float(), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('upload_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_session_session_token'), ['session_token'], unique=True)

    op.create_table('worker_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unc_year', sa.String(length=20), nullable=True),
    sa.Column('role_pref', sa.String(length=20), nullable=True),
    sa.Column('why_blurb', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('worker_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('mon_am', sa.Boolean(), nullable=True),
    sa.Column('mon_pm', sa.Boolean(), nullable=True),
    sa.Column('tue_am', sa.Boolean(), nullable=True),
    sa.Column('tue_pm', sa.Boolean(), nullable=True),
    sa.Column('wed_am', sa.Boolean(), nullable=True),
    sa.Column('wed_pm', sa.Boolean(), nullable=True),
    sa.Column('thu_am', sa.Boolean(), nullable=True),
    sa.Column('thu_pm', sa.Boolean(), nullable=True),
    sa.Column('fri_am', sa.Boolean(), nullable=True),
    sa.Column('fri_pm', sa.Boolean(), nullable=True),
    sa.Column('sat_am', sa.Boolean(), nullable=True),
    sa.Column('sat_pm', sa.Boolean(), nullable=True),
    sa.Column('sun_am', sa.Boolean(), nullable=True),
    sa.Column('sun_pm', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_worker_avail_user_week')
    )
    op.create_table('worker_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('preference_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_user_id', 'preference_type', name='uq_worker_pref')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=3), nullable=False),
    sa.Column('slot', sa.String(length=2), nullable=False),
    sa.Column('trucks', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('truck_unit_plan', sa.Text(), nullable=True),
    sa.Column('sellers_notified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('overflow_truck_number', sa.Integer(), nullable=True),
    sa.Column('reschedule_locked', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['shift_week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutorial_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tutorial_week_id', sa.Integer(), nullable=True),
    sa.Column('last_retake_at', sa.DateTime(), nullable=True),
    sa.Column('is_retaking', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['tutorial_week_id'], ['shift_week.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('collection_method', sa.String(length=20), nullable=True),
    sa.Column('pickup_week', sa.String(length=20), nullable=True),
    sa.Column('dropoff_pod', sa.String(length=40), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('payout_sent', sa.Boolean(), nullable=True),
    sa.Column('payout_sent_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at_store_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=200), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('price_changed_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('storage_row', sa.String(length=50), nullable=True),
    sa.Column('storage_note', sa.Text(), nullable=True),
    sa.Column('unit_size', sa.Float(), nullable=True),
    sa.Column('is_quick_capture', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('quick_capture_shift_id', sa.Integer(), nullable=True),
    sa.Column('captured_by_id', sa.Integer(), nullable=True),
    sa.Column('placement_status', sa.String(length=20), nullable=True),
    sa.Column('needs_photo_refresh', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('needs_new_photo', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_long_description', sa.Text(), nullable=True),
    sa.Column('ai_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ai_retail_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ai_review_pending', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ai_generated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_approved', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['captured_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_category.id'], ),
    sa.ForeignKeyConstraint(['quick_capture_shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['inventory_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('role_on_shift', sa.String(length=20), nullable=False),
    sa.Column('truck_number', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_pickup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.Integer(), nullable=False),
    sa.Column('stop_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('capacity_warning', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('rescheduled_from_shift_id', sa.Integer(), nullable=True),
    sa.Column('rescheduled_at', sa.DateTime(), nullable=True),
    sa.Column('issue_type', sa.String(length=20), nullable=True),
    sa.Column('no_show_email_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_from_shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'seller_id', name='uq_shift_pickup_shift_seller')
    )
    op.create_table('shift_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('started_by_id', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['started_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id')
    )
    op.create_table('buyer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('buyer_email', sa.String(length=120), nullable=False),
    sa.Column('delivery_address', sa.String(length=300), nullable=False),
    sa.Column('delivery_lat', sa.Float(), nullable=True),
    sa.Column('delivery_lng', sa.Float(), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('intake_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('storage_row', sa.String(length=50), nullable=True),
    sa.Column('storage_note', sa.Text(), nullable=True),
    sa.Column('quality_before', sa.Integer(), nullable=False),
    sa.Column('quality_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_email_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reschedule_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_id'], ['shift_pickup.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reschedule_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reschedule_token_token'), ['token'], unique=True)

    op.create_table('seller_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('custom_note', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('intake_record_id', sa.Integer(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('flag_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['intake_record_id'], ['intake_record.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('needs_new_photo')


def _downgrade_unused():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intake_flag')
    op.drop_table('seller_alert')
    with op.batch_alter_table('reschedule_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reschedule_token_token'))

    op.drop_table('reschedule_token')
    op.drop_table('item_reservation')
    op.drop_table('item_photo')
    op.drop_table('intake_record')
    op.drop_table('buyer_order')
    op.drop_table('shift_run')
    op.drop_table('shift_pickup')
    op.drop_table('shift_assignment')
    op.drop_table('inventory_item')
    op.drop_table('tutorial_session')
    op.drop_table('shift')
    op.drop_table('worker_preference')
    op.drop_table('worker_availability')
    op.drop_table('worker_application')
    with op.batch_alter_table('upload_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_session_session_token'))

    op.drop_table('upload_session')
    op.drop_table('storage_location')
    op.drop_table('shift_week')
    op.drop_table('referral')
    op.drop_table('user')
    with op.batch_alter_table('temp_upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_upload_session_token'))

    op.drop_table('temp_upload')
    op.drop_table('shop_notify_signup')
    op.drop_table('inventory_category')
    op.drop_table('digest_log')
    op.drop_table('app_setting')
    op.drop_table('admin_email')
    # ### end Alembic commands ###
