"""Add collection_method to InventoryItem

Revision ID: 859b73104dae
Revises: 35a5d88ba744
Create Date: 2026-02-06 10:12:05.369830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859b73104dae'
down_revision = '35a5d88ba744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('collection_method')

    # ### end Alembic commands ###
