"""route plan mode: separate ops and crew plans

Revision ID: 8f8ee5fbe35d
Revises: c97f8913a9d0
Create Date: 2026-08-13 08:03:11.580035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8ee5fbe35d'
down_revision = 'c97f8913a9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_route_plan',
                  sa.Column('mode', sa.String(length=10), server_default='crew', nullable=False))
    op.drop_constraint('uq_route_plan_shift_truck', 'delivery_route_plan', type_='unique')
    op.create_unique_constraint('uq_route_plan_shift_truck_mode', 'delivery_route_plan',
                                ['shift_id', 'truck_number', 'mode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_route_plan_shift_truck_mode', 'delivery_route_plan', type_='unique')
    op.create_unique_constraint('uq_route_plan_shift_truck', 'delivery_route_plan',
                                ['shift_id', 'truck_number'])
    op.drop_column('delivery_route_plan', 'mode')

    # ### end Alembic commands ###
