"""add_seller_data_preservation_and_photo_enhancement

Revision ID: 9001e2c1e90c
Revises: 765e62e00dca
Create Date: 2026-06-04 19:53:08.316421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9001e2c1e90c'
down_revision = '765e62e00dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seller_long_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_photo_enhanced', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('was_previously_approved', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('was_previously_approved')
        batch_op.drop_column('ai_photo_enhanced')
        batch_op.drop_column('seller_long_description')
        batch_op.drop_column('seller_description')

    # ### end Alembic commands ###
