"""add test_only to scheduled mass email

Revision ID: 9fa5a550a9ca
Revises: 2df60eaf338a
Create Date: 2026-08-18 07:17:42.137654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa5a550a9ca'
down_revision = '2df60eaf338a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_mass_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_only', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_mass_email', schema=None) as batch_op:
        batch_op.drop_column('test_only')

    # ### end Alembic commands ###
