"""add pickup_week to user

Revision ID: a8aa476286fa
Revises: f3be9440440a
Create Date: 2026-04-06 13:25:35.238893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8aa476286fa'
down_revision = 'f3be9440440a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_week', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pickup_week')

    # ### end Alembic commands ###
