"""add pickup_time_preference and moveout_date to user

Revision ID: b5c46df7b729
Revises: dd322174ae00
Create Date: 2026-04-04 22:04:33.861063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c46df7b729'
down_revision = 'dd322174ae00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('inventory_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('count_in_stock', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temp_upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_upload_session_token'), ['session_token'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pickup_address', sa.String(length=200), nullable=True),
    sa.Column('pickup_location_type', sa.String(length=20), nullable=True),
    sa.Column('pickup_dorm', sa.String(length=80), nullable=True),
    sa.Column('pickup_room', sa.String(length=20), nullable=True),
    sa.Column('pickup_note', sa.String(length=200), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('payout_method', sa.String(length=20), nullable=True),
    sa.Column('payout_handle', sa.String(length=100), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_declined', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=120), nullable=True),
    sa.Column('referral_source', sa.String(length=50), nullable=True),
    sa.Column('unsubscribed', sa.Boolean(), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=120), nullable=True),
    sa.Column('pickup_time_preference', sa.String(length=20), nullable=True),
    sa.Column('moveout_date', sa.Date(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('collection_method', sa.String(length=20), nullable=True),
    sa.Column('is_large', sa.Boolean(), nullable=True),
    sa.Column('oversize_included_in_service_fee', sa.Boolean(), nullable=True),
    sa.Column('oversize_fee_paid', sa.Boolean(), nullable=True),
    sa.Column('pickup_week', sa.String(length=20), nullable=True),
    sa.Column('dropoff_pod', sa.String(length=40), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('payout_sent', sa.Boolean(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at_store_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=200), nullable=True),
    sa.Column('video_url', sa.String(length=200), nullable=True),
    sa.Column('price_changed_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_category.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['inventory_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_session_session_token'), ['session_token'], unique=True)

    op.create_table('item_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_email_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_reservation')
    op.drop_table('item_photo')
    with op.batch_alter_table('upload_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_session_session_token'))

    op.drop_table('upload_session')
    op.drop_table('inventory_item')
    op.drop_table('user')
    with op.batch_alter_table('temp_upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_upload_session_token'))

    op.drop_table('temp_upload')
    op.drop_table('inventory_category')
    op.drop_table('app_setting')
    op.drop_table('admin_email')
    # ### end Alembic commands ###
