"""add referral program

Revision ID: c177c356b023
Revises: 6108e1af17ff
Create Date: 2026-04-09 00:18:00.784456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c177c356b023'
down_revision = '6108e1af17ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if 'referral' not in existing_tables:
        op.create_table('referral',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('referrer_id', sa.Integer(), nullable=False),
        sa.Column('referred_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('confirmed', sa.Boolean(), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['referred_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('referred_id')
        )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payout_rate', sa.Integer(), nullable=False, server_default='20'))
        batch_op.create_unique_constraint('uq_user_referral_code', ['referral_code'])
        batch_op.create_foreign_key('fk_user_referred_by_id', 'user', ['referred_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_referred_by_id', type_='foreignkey')
        batch_op.drop_constraint('uq_user_referral_code', type_='unique')
        batch_op.drop_column('payout_rate')
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('referral_code')

    op.drop_table('referral')
    # ### end Alembic commands ###
