"""add delivery_notes to order and buyer_order

Revision ID: c97f8913a9d0
Revises: f65dd72a89fd
Create Date: 2026-08-13 07:45:43.936605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97f8913a9d0'
down_revision = 'f65dd72a89fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_order', sa.Column('delivery_notes', sa.Text(), nullable=True))
    op.add_column('order', sa.Column('delivery_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_notes')
    op.drop_column('buyer_order', 'delivery_notes')

    # ### end Alembic commands ###
