"""add promo_code to order

Revision ID: d23f0806cf8f
Revises: 982051a9ce5d
Create Date: 2026-08-12 20:11:34.077540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23f0806cf8f'
down_revision = '982051a9ce5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('promo_code', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'promo_code')

    # ### end Alembic commands ###
