"""add_proxy_seller_fields

Revision ID: d449caa14176
Revises: 576d29191e72
Create Date: 2026-05-20 12:52:27.629519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd449caa14176'
down_revision = '576d29191e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_proxy_account', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('proxy_temp_password', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('proxy_claim_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('proxy_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proxy_contacted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proxy_claimed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('proxy_note', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint('uq_user_proxy_claim_token', ['proxy_claim_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_proxy_claim_token', type_='unique')
        batch_op.drop_column('proxy_note')
        batch_op.drop_column('proxy_claimed_at')
        batch_op.drop_column('proxy_contacted_at')
        batch_op.drop_column('proxy_token_expires_at')
        batch_op.drop_column('proxy_claim_token')
        batch_op.drop_column('proxy_temp_password')
        batch_op.drop_column('is_proxy_account')

    # ### end Alembic commands ###
