"""add_ai_autofill_fields

Revision ID: da3bed86df50
Revises: 75591ac8d320
Create Date: 2026-05-28 15:36:21.692161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3bed86df50'
down_revision = '75591ac8d320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_long_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ai_review_pending', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ai_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('ai_generated_at')
        batch_op.drop_column('ai_review_pending')
        batch_op.drop_column('ai_price')
        batch_op.drop_column('ai_long_description')
        batch_op.drop_column('ai_description')

    # ### end Alembic commands ###
