"""Add expires_at, cancelled_at, expiry_email_sent to ItemReservation

Revision ID: dd322174ae00
Revises: e74a94f50c39
Create Date: 2026-04-02 22:35:11.568407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd322174ae00'
down_revision = 'e74a94f50c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_reservation', schema=None) as batch_op:
        # Use server_default for existing rows, then remove it
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False, server_default='2025-06-04 00:00:00'))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expiry_email_sent', sa.Boolean(), nullable=True, server_default='0'))

    # Remove server defaults after backfill
    with op.batch_alter_table('item_reservation', schema=None) as batch_op:
        batch_op.alter_column('expires_at', server_default=None)
        batch_op.alter_column('expiry_email_sent', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_reservation', schema=None) as batch_op:
        batch_op.drop_column('expiry_email_sent')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
