"""add exclude_emails to scheduled mass email

Revision ID: e5b417bf82ce
Revises: 309be0f86e10
Create Date: 2026-08-19 06:50:31.379070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b417bf82ce'
down_revision = '309be0f86e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_mass_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclude_emails', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_mass_email', schema=None) as batch_op:
        batch_op.drop_column('exclude_emails')

    # ### end Alembic commands ###
