"""add subcategory support to categories and items

Revision ID: e74a94f50c39
Revises: a882933b0cca
Create Date: 2026-04-02 19:57:17.879310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74a94f50c39'
down_revision = 'a882933b0cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_category_parent', 'inventory_category', ['parent_id'], ['id'])

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_subcategory', 'inventory_category', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_subcategory', type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    with op.batch_alter_table('inventory_category', schema=None) as batch_op:
        batch_op.drop_constraint('fk_category_parent', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
