"""shift_truck_unit_plan

Revision ID: e75123cd96f0
Revises: c054f3e452f6
Create Date: 2026-04-07 21:44:16.583857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75123cd96f0'
down_revision = 'c054f3e452f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_unit_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('truck_unit_plan')

    # ### end Alembic commands ###
