"""remove oversize fee fields

Revision ID: f3be9440440a
Revises: 64b6d59bc796
Create Date: 2026-04-06 13:17:41.044274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3be9440440a'
down_revision = '64b6d59bc796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('oversize_included_in_service_fee')
        batch_op.drop_column('is_large')
        batch_op.drop_column('oversize_fee_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oversize_fee_paid', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_large', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('oversize_included_in_service_fee', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
