"""add delivery_route_plan

Revision ID: f65dd72a89fd
Revises: d23f0806cf8f
Create Date: 2026-08-12 20:49:13.191420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65dd72a89fd'
down_revision = 'd23f0806cf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_route_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.Integer(), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('anchor_label', sa.String(length=200), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('computed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['computed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'truck_number', name='uq_route_plan_shift_truck')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_route_plan')
    # ### end Alembic commands ###
