"""widen_shift_slot_to_varchar6

Revision ID: f66ac32f2876
Revises: 7d66b13ebef5
Create Date: 2026-05-28 23:40:53.175844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66ac32f2876'
down_revision = '7d66b13ebef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_order', schema=None) as batch_op:
        batch_op.alter_column('buyer_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('delivery_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               nullable=False)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reschedule_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reschedule_token_token'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_reschedule_token_token'))
        batch_op.create_index(batch_op.f('ix_reschedule_token_token'), ['token'], unique=True)

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.alter_column('slot',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=6),
               existing_nullable=False)

    with op.batch_alter_table('shift_pickup', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'shift', ['rescheduled_from_shift_id'], ['id'])

    with op.batch_alter_table('upload_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('upload_session_session_token_key'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_unsubscribe_token'))
        batch_op.create_unique_constraint(None, ['unsubscribe_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_user_unsubscribe_token'), ['unsubscribe_token'], unique=True)

    with op.batch_alter_table('upload_session', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('upload_session_session_token_key'), ['session_token'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('shift_pickup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.alter_column('slot',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('reschedule_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reschedule_token_token'))
        batch_op.create_index(batch_op.f('ix_reschedule_token_token'), ['token'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_reschedule_token_token'), ['token'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('buyer_order', schema=None) as batch_op:
        batch_op.alter_column('delivery_address',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('buyer_email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
