"""add_needs_photo_note

Revision ID: fced86d80945
Revises: f66ac32f2876
Create Date: 2026-05-29 00:02:51.251624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fced86d80945'
down_revision = 'f66ac32f2876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_photo_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('needs_photo_note')

    # ### end Alembic commands ###
