"""add_campus_director_role

Revision ID: ffcbf72cb16a
Revises: e5f6a7b8c9d0
Create Date: 2026-05-21 11:46:08.437940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffcbf72cb16a'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_campus_director', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('campus_director_school', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('campus_director_school')
        batch_op.drop_column('is_campus_director')

    # ### end Alembic commands ###
